### PR TITLE
fix(input-number): validate input on typing

### LINKED ISSUE #9: Do not allow invalid input, and make the upper and lower number bounds dynamic
Right now, I can enter whatever I want in the input. This is perhaps not a good user experience.
We should always validate the input to be between the numbers we show.

Also, would be awesome to make the upper and lower limit dynamic so we can perhaps introduce different difficulty levels later 😄

### PR DESCRIPTION
**Pull request by AhsanAyaz**
Fixes #9 

validated input on typing
made the lower and upper number limits dynamic
enhanced the UI a bit

image

### CODE REVIEW

**Comment by AhsanAyaz** [comment]
@coolpythoncodes please add the label `hacktoberfest-accepted` once you've reviewed the changes.
Looking forward to seeing this merged 🙂

**Comment by coolpythoncodes** [comment]
There is a conflict somewhere. Pls check your code

**Comment by AhsanAyaz** [comment]
@coolpythoncodes because you merged a similar  PR someone else created after me 🙂

**Comment by AhsanAyaz** [comment]
@coolpythoncodes please add `hacktoberfest-accepted` label to this PR and merge.
Resolved the conflicts :)

**Pull request merged**
